blink_favicon_data_uri <- function() {
  paste0(
    "data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22%3E",
    "%3Cdefs%3E%3ClinearGradient id=%22g%22 x1=%220%22 x2=%221%22 y1=%220%22 y2=%221%22%3E",
    "%3Cstop stop-color=%22%234f46e5%22/%3E%3Cstop offset=%221%22 stop-color=%22%230ea5e9%22/%3E%3C/linearGradient%3E%3C/defs%3E",
    "%3Crect width=%2264%22 height=%2264%22 rx=%2216%22 fill=%22url(%23g)%22/%3E",
    "%3Cpath d=%22M18 44V18h17c7 0 11 4 11 9 0 3-2 6-5 7 4 1 6 4 6 8 0 6-5 10-13 10H18zm10-16h6c3 0 5-1 5-4s-2-4-5-4h-6v8zm0 18h8c3 0 5-2 5-5s-2-5-6-5h-7v10z%22 fill=%22white%22/%3E%3C/svg%3E"
  )
}

blink_index_html <- function(title) {
  title <- blink_escape_html(title %||% "BlinkDash")
  paste0(
'<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="blinkdash">
  <title>', title, '</title>
  <link rel="icon" href="', blink_favicon_data_uri(), '">
  <link rel="stylesheet" href="assets/blinkdash.css">
</head>
<body>
  <noscript>This dashboard needs JavaScript enabled.</noscript>
  <main id="blinkdash-root" class="bd-root"></main>
  <script src="data/app-data.js"></script>
  <script src="assets/webr-bridge.js"></script>
  <script src="assets/blinkdash.js"></script>
</body>
</html>
'
  )
}

blink_pages_workflow <- function(path = ".") {
  paste0(
'name: Deploy BlinkDash to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "', path, '"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
'
  )
}

blink_export_readme <- function(title) {
  paste0(
"# ", title %||% "BlinkDash dashboard", "\n\n",
"This directory was generated by `blinkdash`. It is a static dashboard: HTML, CSS, JavaScript, and embedded JSON data.\n\n",
"For a GitHub user or organization Pages repository named `username.github.io`, commit these files at the repository root. For a project repository, enable GitHub Pages for the root or use the included workflow.\n"
  )
}

#' Export a static dashboard
#'
#' @param project A manifest list, a `dashboard.blink.yml`/`dashboard.blink.json` file, or a dashboard project directory.
#' @param out_dir Output directory. For the lowest-friction GitHub Pages path, use the repository root of a `username.github.io` repo.
#' @param include_workflow Whether to include a GitHub Pages workflow.
#' @param overwrite Whether to overwrite existing generated files.
#'
#' @return The output directory, invisibly.
#' @export
export_dashboard <- function(project, out_dir = "site", include_workflow = TRUE, overwrite = TRUE) {
  manifest <- blink_read_manifest(project)
  title <- manifest$title %||% "BlinkDash"
  out_dir <- normalizePath(out_dir, mustWork = FALSE)
  if (file.exists(out_dir) && !dir.exists(out_dir)) stop("`out_dir` exists and is not a directory.", call. = FALSE)
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  assets_src <- blink_pkg_file("export", "assets")
  blink_copy_dir_contents(assets_src, file.path(out_dir, "assets"))
  dir.create(file.path(out_dir, "data"), recursive = TRUE, showWarnings = FALSE)

  app_json <- blink_json(blink_manifest_for_save(manifest), pretty = FALSE)
  blink_write_utf8(paste0("window.BLINKDASH_APP = ", app_json, ";\n"), file.path(out_dir, "data", "app-data.js"))
  blink_write_utf8(blink_index_html(title), file.path(out_dir, "index.html"))
  blink_write_utf8("", file.path(out_dir, ".nojekyll"))
  blink_write_utf8(blink_export_readme(title), file.path(out_dir, "README.md"))
  blink_write_utf8(blink_index_html(title), file.path(out_dir, "404.html"))

  if (isTRUE(include_workflow)) {
    wf_dir <- file.path(out_dir, ".github", "workflows")
    dir.create(wf_dir, recursive = TRUE, showWarnings = FALSE)
    blink_write_utf8(blink_pages_workflow("."), file.path(wf_dir, "pages.yml"))
  }

  invisible(out_dir)
}
