#' Widget registry
#'
#' Returns widget/component types available in the visual builder shelf.
#'
#' @return A data frame with widget metadata.
#' @export
widget_registry <- function() {
  data.frame(
    type = c(
      "selectize", "select", "multiselect", "slider", "range", "date", "daterange",
      "checkbox", "radio", "search", "text", "number", "toggle", "button",
      "metric", "table", "scatter", "line", "bar", "histogram",
      "boxplot", "heatmap", "pie", "markdown", "html", "webr", "rplot"
    ),
    role = c(rep("input", 14), rep("output", 13)),
    shelf = c(
      rep("Inputs", 14),
      "Indicators", "Tables", rep("Plots", 7), "Narrative", "Narrative", "R and webR", "R and webR"
    ),
    label = c(
      "Selectize", "Select", "Multi-select", "Slider", "Range slider", "Date filter", "Date range",
      "Checkboxes", "Radio buttons", "Search", "Text filter", "Number filter", "Toggle", "Button",
      "Metric", "Table", "Scatter", "Line", "Bar", "Histogram",
      "Box plot", "Heatmap", "Pie or donut", "Markdown", "Trusted HTML", "webR processor", "R plot viewer"
    ),
    description = c(
      "Styled searchable single or multi-choice categorical input",
      "Single-choice dropdown",
      "Native multi-choice dropdown",
      "Numeric slider",
      "Dual-thumb numeric min-max ruler",
      "Date comparator",
      "Date start-end range",
      "Checkbox group for categorical values",
      "Radio group for one categorical value",
      "Dataset search box",
      "Text input or contains filter",
      "Numeric comparator with configurable minimum, maximum, and step",
      "Boolean/logical toggle",
      "Action button",
      "KPI card",
      "Sortable paged table with CSV download",
      "Canvas scatter plot",
      "Canvas line plot with legend",
      "Canvas bar chart with color, sort, and hover options",
      "Canvas histogram with touching bins and configurable bin count",
      "Canvas box plot",
      "Canvas heatmap",
      "Canvas pie or donut chart",
      "Markdown block with fenced code, math, Mermaid diagrams, and input placeholders",
      "Trusted HTML block rendered directly; can use input placeholders and soft-wrapped editing",
      "Client-side R snippet using webR with soft-wrapped editing; accepts input links and can feed Markdown, HTML, Table, and R plot viewers",
      "Viewer for SVG-first plots generated by an upstream webR processor"
    ),
    sourcePort = c(rep(TRUE, 14), rep(FALSE, 11), TRUE, FALSE),
    targetPort = c(rep(FALSE, 14), rep(TRUE, 13)),
    stringsAsFactors = FALSE
  )
}
